image: node:8.6.0 

cache:
  paths:
    - node_modules/

before_script:
  - yarn install

test:
  stage: test
  script:
    - yarn test -- --coverage
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

pages:
  stage: deploy
  script:
    - yarn run build:prod
    - rm -rf public
    - mv dist/ public/
  artifacts:
    paths:
      - public 
  only:
    - master 