image: node:8.6.0 

cache:
  paths:
    - node_modules/

before_script:
  - npm install

# test:
#   stage: test
#   script:
#     - CI=true npm test

pages:
  stage: deploy
  script:
    - npm run build:prod
    - rm -rf public
    - mv dist/ public/
  artifacts:
    paths:
      - public 
  only:
    - master 