language: node_js

node_js:
   "8.6.0"

cache:
  directories:
    - node_modules
  yarn: true

install:
  - yarn install

script:
  - yarn test
  - yarn run build:prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  email: ritwickdey@outlook.com
  name: Ritwick Dey
  target-branch: gh-pages
  on:
    branch: master